<template>
  <div>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
      <p>youce</p>
  </div>
</template>

<script>
export default {
    name:'categoryRight'
}
</script>

<style>

</style>